### PR TITLE
Add Symfony 3 support

### PR DESCRIPTION
**Pull request by WouterJ**

### CODE REVIEW

**Comment by Burgov** [comment]
These if statements and checks for methods and classes look kinda hacky to me. Is this really the way to build sth that's compatible with both? (This is just a small library, I can't imagine the hell in a big one)

**Comment by WouterJ** [comment]
Unfortunately, yes it is if you want 2.3 *and* 3.0 support (methods of 3.0 aren't available in 2.3 and methods available in 2.3 are removed in 3.0).

This is why I expect many bundles to support 2.3 - 2.8 or 2.8 & 3.0, but not the complete 2.x serie and 3.0 (the CMF is going to do this btw).

**Comment by Burgov** [comment]
Ok, at some point we should bump the major on this bundle and discontinue 2.x support, but that's far ahead I suppose.

**Comment by WouterJ** [comment]
Yeah. For the most part, supporting 2.6+ is already enough (only the `getName` -> `getBlockPrefix` renaming requires 2.8+).

**Pull request merged**
