### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by carlos-granados**
Explain that you need to use branch 1.2.0 for Symfony 2. I spent a long time debugging this bundle until I realized this

### CODE REVIEW

**Comment by Burgov** [comment]
hmm... shouldn't it actually just work in Symfony 2 @WouterJ ?

**Comment by WouterJ** [comment]
Yes, I would like to know the error/problem when using this bundle in a 2.x application. afaik, there shouldn't be any problem.

**Comment by carlos-granados** [comment]
If I use any version higher than 1.2.0 I get a "The required option "value_type" is missing." even though this option is there. Not really sure why, I guess it has to do with the changes you did to adapt it for Symfony 3

**Comment by WouterJ** [comment]
@carlos-granados are you sure you use the latest 2.8 version? Seems like a bug that was fixed in Symfony 2.8.2.

**Comment by carlos-granados** [comment]
We are currently on Symfony 2.8.1, so that is probably the issue. I'll close this

**Comment by Burgov** [comment]
The composer.json contains a line that says it conflicts with symfony-forms 2.8.1, but apparently that's not doing anything then? @WouterJ @seldaek any idea?

**Comment by WouterJ** [comment]
@Burgov probably, an older version is simply installed.

**Pull request closed without merging**
