### PR TITLE
Use FQCN instead of form name in Symfony 2.8+

### PR DESCRIPTION
**Pull request by WouterJ**
While testing with the Symfony CMF on Symfony 3, I found that this bundle has some issues with Symfony 3 support. I hope this PR has fixed them all.

@Burgov I cannot make much sense of the tests and have a real hard time getting them pass on Symfony 3. Can you please fix these tests? (dropping Symfony 2.3 support would help quite a lot and please note that it'll reach end of maintaince this month)

### CODE REVIEW

**Comment by WouterJ** [comment]
@Burgov can you please review and merge this one or #22?

**Comment by Burgov** [comment]
I've merged #22 as it includes documentation

**Comment by WouterJ** [comment]
@Burgov  can you please then merge https://github.com/Burgov/KeyValueFormBundle/pull/25 (which fixes PHP <5.5 compat and also fixes the other form type)

**Comment by Burgov** [comment]
Done. Please verify if everything is alright. I'm currently not in the position to do so myself

**Comment by WouterJ** [comment]
This are working as expected in the CMF sandbox now, so I assume it's alright.

As said in this PR description, I'm unable to make the tests pass in any way (mostly because I don't understand what they are testing). You probably have to take a look at time once you have some spare time.

**Pull request closed without merging**
